# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 446  #https端口
  servlet:
    context-path: /app-api
  http:  #http 端口
    port: 8083
  connection-timeout: 18000000
  ssl:
    key-store: classpath:www-ubfly-projks.jks
    key-store-password:
    key-store-type: JKS
    key-alias: 1
  #domain: www.jhdriver.org
  #domain: 47.75.241.214
  domain: 172.20.20.82
# mysql
spring:
  # 环境 dev|main|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 200MB
      enabled: true
renren:
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭

config:
  jwt:
    secret: abcdefg1234567
    #token有效时长 单位：s
    expire: 36000
    #header名称
    header: token
  debug: false



#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cube.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'



